<?php
$namaserver="localhost";
$userdb="root";
$passdb="";
$namadb="perpustakaan";
$koneksi=mysqli_connect($namaserver,$userdb,$passdb,$namadb);
$queri="INSERT INTO buku
(buku_kode,
kategori_kode,
penerbit_kode,
buku_judul,
buku_jumhal,
buku_diskripsi,
buku_pengarang,
buku_thn_terbit) 
VALUES 
('$_POST[kode]',
'$_POST[kode_kategori]',
'$_POST[kode_penerbit]',
'$_POST[judul]',
'$_POST[jumlah]',
'$_POST[diskripsi]',
'$_POST[pengarang]',
'$_POST[tahun]')";
mysqli_query($koneksi,$queri);
mysqli_close($koneksi);
header('location:buku.php');
?>